name: Python Pipeline

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: action@checkoutv3
      - run: python app.py
      
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: action@checkoutv3
      - uses: action@upload-artifact@v3
        with: 
          name: app
          path: .