name: GitHub Actions Demo
on: [push]
jobs:
  Print-Date-On-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The date is $(date)"
  Print-Date-on-Windows:
    runs-on: windows-latest
    steps:
      - run: Get-Date
  Print-Date-On-MacOs:
    runs-on: macos-latest
    steps:
      - run: echo "Date is $(date)"