name: GitHub Actions Demo
on: [push]
jobs:
  Print-Basic-Details:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      - name: Print name
        uses: actions/checkout@v3
      - run: echo "Hi Raja"